apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: saksbehandling-pdfgen
  namespace: aap
  labels:
    team: aap
spec:
  accessPolicy:
    inbound:
      rules:
        - application: saksbehandling
        - application: brev
        - application: postmottak
  image: {{ image }}
  ingresses:
    - https://aap-saksbehandling-pdfgen.intern.nav.no
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 80
  liveness:
    path: /internal/is_alive
  readiness:
    path: /internal/is_ready
  prometheus:
    enabled: true
    path: /prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: "java"
    logging:
      destinations:
        - id: elastic
        - id: loki
